### PR TITLE
Cleanified PKCS1toPCKCS8pubkey ...

### PR DESCRIPTION
**Pull request by subho007**
@dhilipsiva test & merge this, and then push it to pypi

### CODE REVIEW

**Comment by ChillarAnand** [comment]
thread safe?

**Comment by subho007** [comment]
@ChillarAnand doesn't matter, because this fixes a problem, when the `idevice` is not paired correctly.

**Comment by dhilipsiva** [comment]
@ChillarAnand Lets test this when you are office today.

**Comment by ChillarAnand** [comment]
:+1:

**Pull request merged**
